/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated/scripts'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin/categorias'
import { Route as AuthenticatedAdminComunicadosRouteImport } from './routes/_authenticated/admin/comunicados'
import { Route as AuthenticatedAdminScriptsRouteImport } from './routes/_authenticated/admin/scripts'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedEmpreendimentosIndexRouteImport } from './routes/_authenticated/empreendimentos/index'
import { Route as AuthenticatedEmpreendimentosSlugRouteImport } from './routes/_authenticated/empreendimentos/$slug'
import { Route as AuthenticatedAdminEmpreendimentosIndexRouteImport } from './routes/_authenticated/admin/empreendimentos/index'
import { Route as AuthenticatedAdminEmpreendimentosIdRouteImport } from './routes/_authenticated/admin/empreendimentos/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminComunicadosRoute =
  AuthenticatedAdminComunicadosRouteImport.update({
    id: '/comunicados',
    path: '/comunicados',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminScriptsRoute =
  AuthenticatedAdminScriptsRouteImport.update({
    id: '/scripts',
    path: '/scripts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedEmpreendimentosIndexRoute =
  AuthenticatedEmpreendimentosIndexRouteImport.update({
    id: '/empreendimentos/',
    path: '/empreendimentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpreendimentosSlugRoute =
  AuthenticatedEmpreendimentosSlugRouteImport.update({
    id: '/empreendimentos/$slug',
    path: '/empreendimentos/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmpreendimentosIndexRoute =
  AuthenticatedAdminEmpreendimentosIndexRouteImport.update({
    id: '/empreendimentos/',
    path: '/empreendimentos/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmpreendimentosIdRoute =
  AuthenticatedAdminEmpreendimentosIdRouteImport.update({
    id: '/empreendimentos/$id',
    path: '/empreendimentos/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/comunicados': typeof AuthenticatedAdminComunicadosRoute
  '/admin/scripts': typeof AuthenticatedAdminScriptsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/empreendimentos/$slug': typeof AuthenticatedEmpreendimentosSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/empreendimentos/': typeof AuthenticatedEmpreendimentosIndexRoute
  '/admin/empreendimentos/$id': typeof AuthenticatedAdminEmpreendimentosIdRoute
  '/admin/empreendimentos/': typeof AuthenticatedAdminEmpreendimentosIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/comunicados': typeof AuthenticatedAdminComunicadosRoute
  '/admin/scripts': typeof AuthenticatedAdminScriptsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/empreendimentos/$slug': typeof AuthenticatedEmpreendimentosSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosIndexRoute
  '/admin/empreendimentos/$id': typeof AuthenticatedAdminEmpreendimentosIdRoute
  '/admin/empreendimentos': typeof AuthenticatedAdminEmpreendimentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/comunicados': typeof AuthenticatedAdminComunicadosRoute
  '/_authenticated/admin/scripts': typeof AuthenticatedAdminScriptsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/empreendimentos/$slug': typeof AuthenticatedEmpreendimentosSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/empreendimentos/': typeof AuthenticatedEmpreendimentosIndexRoute
  '/_authenticated/admin/empreendimentos/$id': typeof AuthenticatedAdminEmpreendimentosIdRoute
  '/_authenticated/admin/empreendimentos/': typeof AuthenticatedAdminEmpreendimentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/perfil'
    | '/scripts'
    | '/admin/categorias'
    | '/admin/comunicados'
    | '/admin/scripts'
    | '/admin/usuarios'
    | '/empreendimentos/$slug'
    | '/admin/'
    | '/empreendimentos/'
    | '/admin/empreendimentos/$id'
    | '/admin/empreendimentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/perfil'
    | '/scripts'
    | '/'
    | '/admin/categorias'
    | '/admin/comunicados'
    | '/admin/scripts'
    | '/admin/usuarios'
    | '/empreendimentos/$slug'
    | '/admin'
    | '/empreendimentos'
    | '/admin/empreendimentos/$id'
    | '/admin/empreendimentos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/perfil'
    | '/_authenticated/scripts'
    | '/_authenticated/'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/comunicados'
    | '/_authenticated/admin/scripts'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/empreendimentos/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/empreendimentos/'
    | '/_authenticated/admin/empreendimentos/$id'
    | '/_authenticated/admin/empreendimentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/comunicados': {
      id: '/_authenticated/admin/comunicados'
      path: '/comunicados'
      fullPath: '/admin/comunicados'
      preLoaderRoute: typeof AuthenticatedAdminComunicadosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/scripts': {
      id: '/_authenticated/admin/scripts'
      path: '/scripts'
      fullPath: '/admin/scripts'
      preLoaderRoute: typeof AuthenticatedAdminScriptsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/empreendimentos/': {
      id: '/_authenticated/empreendimentos/'
      path: '/empreendimentos'
      fullPath: '/empreendimentos/'
      preLoaderRoute: typeof AuthenticatedEmpreendimentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empreendimentos/$slug': {
      id: '/_authenticated/empreendimentos/$slug'
      path: '/empreendimentos/$slug'
      fullPath: '/empreendimentos/$slug'
      preLoaderRoute: typeof AuthenticatedEmpreendimentosSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/empreendimentos/': {
      id: '/_authenticated/admin/empreendimentos/'
      path: '/empreendimentos'
      fullPath: '/admin/empreendimentos/'
      preLoaderRoute: typeof AuthenticatedAdminEmpreendimentosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/empreendimentos/$id': {
      id: '/_authenticated/admin/empreendimentos/$id'
      path: '/empreendimentos/$id'
      fullPath: '/admin/empreendimentos/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmpreendimentosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminComunicadosRoute: typeof AuthenticatedAdminComunicadosRoute
  AuthenticatedAdminScriptsRoute: typeof AuthenticatedAdminScriptsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEmpreendimentosIdRoute: typeof AuthenticatedAdminEmpreendimentosIdRoute
  AuthenticatedAdminEmpreendimentosIndexRoute: typeof AuthenticatedAdminEmpreendimentosIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
    AuthenticatedAdminComunicadosRoute: AuthenticatedAdminComunicadosRoute,
    AuthenticatedAdminScriptsRoute: AuthenticatedAdminScriptsRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminEmpreendimentosIdRoute:
      AuthenticatedAdminEmpreendimentosIdRoute,
    AuthenticatedAdminEmpreendimentosIndexRoute:
      AuthenticatedAdminEmpreendimentosIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEmpreendimentosSlugRoute: typeof AuthenticatedEmpreendimentosSlugRoute
  AuthenticatedEmpreendimentosIndexRoute: typeof AuthenticatedEmpreendimentosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEmpreendimentosSlugRoute: AuthenticatedEmpreendimentosSlugRoute,
  AuthenticatedEmpreendimentosIndexRoute:
    AuthenticatedEmpreendimentosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
